BitBookProj/BitBookProj/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BitBookProj.Models
{
    public class User
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "First Name Required")]
        [DisplayName("First Name")]
        [StringLength(20, MinimumLength = 3,ErrorMessage = "First Name Must be 3-20 chracter")]
        [Column(TypeName = "varchar")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Last Name Required")]
        [DisplayName("Last Name")]
        [StringLength(20, MinimumLength = 3, ErrorMessage = "Last Name Must be 3-20 chracter")]
        [Column(TypeName = "varchar")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Email is Required")]
        [DataType(DataType.EmailAddress)]
        [RegularExpression(@"[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?", ErrorMessage = "Please provide valid email")]
        [Remote("IsEmailExist","Users",ErrorMessage = "Email already used")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Select gender")]
        public string Gender { get; set; }
        [Required(ErrorMessage = "Date of Birth Required")]
        [DataType(DataType.Date)]
        [DisplayName("Date of Birth")]
        public DateTime DateOfBirth { get; set; }
        [Required(ErrorMessage = "Password must required")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Required(ErrorMessage = "Please provide your confirm password")]
        [DisplayName("Confirm Password")]
        [System.ComponentModel.DataAnnotations.Compare("Password",ErrorMessage = "Must be same with password")]
        [NotMapped]
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }

        public byte[] ProfilePic { get; set; }
        public byte[] CoverPic { get; set; }
        public string City { get; set; }

        public string Country { get; set; }
        public virtual List<Friend> Friends { get; set; }
        public virtual List<Status> Statuses { get; set; }
        public virtual List<Comment> Comments { get; set; }
        public virtual List<Like> Liks { get; set; }


    }
}

BitBookProj/BitBookProj/Controllers/StatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BitBookProj.BLL;
using BitBookProj.Models;

namespace BitBookProj.Controllers
{
    public class StatusController : Controller
    {
       

         [HttpPost]
        public ActionResult PostStatus([Bind(Include = "UserId, Text")]Status status)
        {
            
            status.Date=DateTime.Now;
            StatusManager statusManager=new StatusManager();
            if (ModelState.IsValid)
            {
                statusManager.Add(status);
            }
            return RedirectToAction("NewsFeed", "Users");
        }

        public ActionResult LikeStatus([Bind(Include = "UserId,StatusId")] Like like)
        {
            LikeManager likeManager=new LikeManager();
            if (ModelState.IsValid)
            {
                likeManager.Add(like);
            }
            return RedirectToAction("NewsFeed", "Users");
        }
    }
}

BitBookProj/BitBookProj/Controllers/UsersController.cs
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using BitBookProj.BLL;
using BitBookProj.Models;
//using System.Web.UI.WebControls;

namespace BitBookProj.Controllers
{
    public class UsersController : Controller
    {
        private readonly FriendManager _friendManager = new FriendManager();

        private readonly UserManager _userManager = new UserManager();
        private readonly BitBookDbContext db = new BitBookDbContext();

        // GET: Users
        [Authorize]
        public ActionResult Index()
        {
            var users = _userManager.GetAll();
            return View(users);
        }

        [Authorize]
        public ActionResult ChangePassword()
        {
            var user = _userManager.GetByEmail(User.Identity.Name);
            return View(user);
        }

        [HttpPost]
        [Authorize]
        public ActionResult ChangePassword(string Password, string ConfirmPassword)
        {
            if (Password.Trim() == ConfirmPassword.Trim())
            {
                var user = _userManager.GetByEmail(User.Identity.Name);
                user.Password = Password.Trim();
                user.ConfirmPassword = Password.Trim();
                if (_userManager.Update(user))
                    return RedirectToAction("NewsFeed");
                return View();
            }

            return View();
        }

        [Authorize]
        public ActionResult NewsFeed(int? friendId)
        {
            var user = new User();
            if (friendId == null)
                user = _userManager.GetByEmail(User.Identity.Name);
            else
                user = _userManager.GetById((int) friendId);
            ViewBag.LoginUser = _userManager.GetByEmail(User.Identity.Name);
            var statusManager = new StatusManager();
            ViewBag.StatusList = statusManager.GetStatusById(user.Id);

            return View(user);
        }

        [Authorize]
        public ActionResult Timeline()
        {
            var user = _userManager.GetByEmail(User.Identity.Name);

            var statusManager = new StatusManager();
            ViewBag.StatusList = statusManager.GetStatusById(user.Id);

            return View(user);
        }

        public JsonResult IsEmailExist(string email)
        {
            return Json(!db.Users.Any(c => c.Email == email), JsonRequestBehavior.AllowGet);
        }

        public ActionResult Search(string name)
        {
            var users = _userManager.GetBySearchString(name);

            return View(users);
        }

        [HttpPost]
        public ActionResult AddFriend(int friendId)
        {
            var user = _userManager.GetByEmail(User.Identity.Name);
            var friend = new Friend();
            friend.User1Id = user.Id;
            friend.User2Id = friendId;
            friend.IsAccepted = false;

            _friendManager.sendFriendRequest(friend);
            return RedirectToAction("Search");
        }

        public ActionResult MyFriends()
        {
            var user = _userManager.GetByEmail(User.Identity.Name);
            var friends = _friendManager.FriendList(user);
            return View(friends);
        }

        public ActionResult ReceivedRequests()
        {
            var user = _userManager.GetByEmail(User.Identity.Name);
            var friends = _friendManager.ReceivedRequest(user);
            return View(friends);
        }

        public ActionResult Accept(int friendId)
        {
            var user = _userManager.GetByEmail(User.Identity.Name);
            var friend = _friendManager.GetReceivedFriendById(friendId, user.Id);
            friend.IsAccepted = true;
            _friendManager.AcceptFriend(friend);
            return RedirectToAction("ReceivedRequests");
        }

        public ActionResult Unfriend(int friendId)
        {
            var user = _userManager.GetByEmail(User.Identity.Name);
            var friend = _friendManager.GetFriendById(friendId, user.Id);
            _friendManager.RemoveFriend(friend);
            return RedirectToAction("MyFriends");
        }

        // GET: Users/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var user = _userManager.GetById((int) id);
            if (user == null)
                return HttpNotFound();
            return View(user);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("NewsFeed");
            }
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(
            [Bind(Include = "Id,FirstName,LastName,Email,Gender,DateOfBirth,Password,ConfirmPassword,City,Country")] User user)
        {
            if (ModelState.IsValid)
            {
                _userManager.Add(user);
                return RedirectToAction("Index");
            }

            return View(user);
        }


        public ActionResult Login()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("NewsFeed");
            }
                
            return View();
        }

        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut();
            Response.Cache.SetNoStore();
            return RedirectToAction("Login");
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Login(string lEmail, string lPassword)
        {
            var u = _userManager.GetByEmail(lEmail);
            if (u.Password == lPassword)
            {
                ViewBag.msg = null;
                FormsAuthentication.SetAuthCookie(u.Email, false);
                return RedirectToAction("NewsFeed");
            }
            ViewBag.msg = "Wrong Email or Password";
            return View();
        }

        // GET: Users/Edit/5
        [Authorize]
        public ActionResult Edit()
        {
            var user = _userManager.GetByEmail(User.Identity.Name);
            if (user == null)
                return HttpNotFound();
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit(
            [Bind(Include = "Id,FirstName,LastName,DateOfBirth,City,Country")] User user)
        {
            User myUser = _userManager.GetById(user.Id);
            myUser.FirstName = user.FirstName;
            myUser.LastName = user.LastName;
            myUser.DateOfBirth = user.DateOfBirth;
            myUser.City = user.City;
            myUser.Country = user.Country;
            myUser.ConfirmPassword = myUser.Password;
            if(_userManager.Update(myUser))
                    return RedirectToAction("NewsFeed");
            return View(myUser); ;
           
        }

        // GET: Users/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var user = _userManager.GetById((int) id);
            if (user == null)
                return HttpNotFound();
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            var user = _userManager.GetById(id);
            _userManager.Delete(user);
            return RedirectToAction("Index");
        }

        //image upload
        public ActionResult ChangeProfilePic(HttpPostedFileBase ProfilePic)
        {
            if (ProfilePic != null)
            {
                var myPic = Image.FromStream(ProfilePic.InputStream, true, true);
                var imageInBytes = imageToByteArray(myPic);
           
                var user = _userManager.GetByEmail(User.Identity.Name);
                user.ConfirmPassword = user.Password;
                user.ProfilePic = imageInBytes;
                _userManager.Update(user);
            }
            
            return RedirectToAction("NewsFeed");
        }

        public ActionResult ChangeCoverPic(HttpPostedFileBase CoverPic)
        {
            
            if (CoverPic != null)
            {
                var myPic = Image.FromStream(CoverPic.InputStream, true, true);
                var imageInBytes = imageToByteArray(myPic);
                var user = _userManager.GetByEmail(User.Identity.Name);
                user.ConfirmPassword = user.Password;
                user.CoverPic = imageInBytes;
                _userManager.Update(user);
            }
            
            return RedirectToAction("NewsFeed");
        }

        //image to byte converter
        private byte[] imageToByteArray(Image imageIn)
        {
            var ms = new MemoryStream();
            imageIn.Save(ms, ImageFormat.Gif);
            return ms.ToArray();
        }

        //byte to image converter
        public ActionResult byteArrayToImage(byte[] byteArrayIn)
        {
            //Image returnImage = null;
            //using (MemoryStream ms = new MemoryStream(byteArrayIn))
            //{

BitBookProj/BitBookProj/Views/Users/ChangePassword.cshtml
@model BitBookProj.Models.User

@{
    ViewBag.Title = "ChangePassword";
}

<h2>Change Password</h2>

@using (Html.BeginForm("ChangePassword","Users",FormMethod.Post ,new { id = "changePasswordform" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Change your Password</h4>
        <hr />
       
        <div class="form-group">
            @Html.Label("Password", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Editor("Password", new { htmlAttributes = new { @class = "form-control" } })
                @*@Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })*@
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Editor("ConfirmPassword", new { htmlAttributes = new { @class = "form-control" } })
                @*@Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })*@
            </div>
        </div>
      
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<script>
    $(document)
        .ready(function() {
            $("#changePasswordform")
                .validate({
                    rules: {
                        Password: {
                            required: true,
                            minlength: 6
                        },
                        ConfirmPassword: {
                            required: true,
                            minlength: 6,
                            equalTo: "#Password"
                        }
                    },
                    messages: {
                        Password: {
                            required: "Please provide a password",
                            minlength: "Your password must be at least 6 characters long"
                        },
                        ConfirmPassword: {
                            required: "Please provide a password",
                            minlength: "Your password must be at least 6 characters long",
                            equalTo: "Please enter the same password as above"
                        }
                    }
                });
        });
</script>

BitBookProj/BitBookProj/Views/Users/Delete.cshtml
@model BitBookProj.Models.User

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BitBookProj/BitBookProj/Views/Users/Details.cshtml
@model BitBookProj.Models.User

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BitBookProj/BitBookProj/Views/Users/Edit.cshtml
@model BitBookProj.Models.User

@{
    ViewBag.Title = "Profile Update";
}
<div style="margin-top: 100px"></div>
<h2>Update Info</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-default" />
            </div>
        </div>
    </div>
}

BitBookProj/BitBookProj/Views/Users/NewsFeed.cshtml
@using BitBookProj.Models
@model BitBookProj.Models.User
@{
    //Layout = null;

    User loginUser = ViewBag.LoginUser;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>BitBook</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" media="screen"/>
    <link href="~/Content/StyleSheet.css" rel="stylesheet"/>
    <link href="~/Content/customize.css" rel="stylesheet"/>
</head>
<body>
<div style="margin-top: 100px"></div>

<div class="container-fluid">
<div class="row">
<div class="col-lg-3">

    <div class="side-menu">

        <nav class="navbar navbar-default" role="navigation">
            <!-- Main Menu -->
            <div class="side-menu-container">
                <ul class="nav navbar-nav">
                    <li>
                        @if (Model.ProfilePic != null)
                        {
                            var base64 = Convert.ToBase64String(Model.ProfilePic);
                            var imgSrc = string.Format("data:image/gif;base64,{0}", base64);

                            <a href="#">
                                <img src="@imgSrc" class="lgo img-rounded" style="width: 50%"/>
                            </a>
                        }
                        else
                        {
                            <a href="#">
                                <img src="~/img/person.png" class="lgo img-rounded" style="width: 50%"/>
                            </a>
                        }

                    </li>
                    <li>

                        @if (loginUser.Id == Model.Id)
                        {
                            using (Html.BeginForm("ChangeProfilePic", "Users", FormMethod.Post, new {enctype = "multipart/form-data"}))
                            {
                                <div class="row">
                                    <span class="span4">
                                                <input type="file" name="ProfilePic" class="input-files" />
                                            </span>
                                    <span class="span2">
                                                <input type="submit" name="profilePic" value="Upload" class="btn btn-upload" />
                                            </span>
                                </div>
                            }
                        }

                    </li>
                    <li>
                        <h3>@Model.FirstName @Model.LastName</h3>
                    </li>
                    <li>
                        @Html.ActionLink("Friends", "MyFriends", "Users", new {htmlAttributes = new {@class = "btn btn-default "}})
                    </li>
                    <!-- Dropdown-->
                    <li class="panel panel-default" id="dropdown">
                        <a data-toggle="collapse" href="#dropdown-lvl1">
                            <span class="glyphicon glyphicon-user"></span> About <span class="caret"></span>
                        </a>

                        <!-- Dropdown level 1 -->
                        <div id="dropdown-lvl1" class="panel-collapse collapse">
                            <div class="panel-body">
                                <ul class="nav navbar-nav">
                                    <li>
                                        <a href="#">@Model.Email</a>
                                    </li>
                                    <li>
                                        <a href="#">@Model.DateOfBirth.ToShortDateString()</a>
                                    </li>
                                    <li>
                                        <a href="#">@Model.Gender</a>
                                    </li>
                                    @*<li>
                                                <a href="#">Dhaka</a>
                                            </li>
                                            <li>
                                                <a href="#">Bangladesh</a>
                                            </li>*@

                                    <!-- Dropdown level 2 -->
                                    @*<li class="panel panel-default" id="dropdown">
                                        <a data-toggle="collapse" href="#dropdown-lvl2">
                                            <span class="glyphicon glyphicon-off"></span> Sub Level <span class="caret"></span>
                                        </a>
                                        <div id="dropdown-lvl2" class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <ul class="nav navbar-nav">
                                                    <li>
                                                        <a href="#">Link</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Link</a>
                                                    </li>
                                                    <li>
                                                        <a href="#">Link</a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </li>*@
                                </ul>
                            </div>
                        </div>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </nav>
    </div>

</div>
<div class="col-lg-9">
    <div class="row">
        <div class="col-lg-12">
            <div class="timeline-cover">

                @if (Model.CoverPic != null)
                {
                    var base64 = Convert.ToBase64String(Model.CoverPic);
                    var imgSrc = string.Format("data:image/gif;base64,{0}", base64);

                    <img src="@imgSrc" style="height: 300px; width: 900px;" class="img-responsive img-thumbnail"/>
                }
                else
                {
                    <img src="~/img/car.png" style="height: 300px; width: 900px;" class="img-responsive img-thumbnail"/>
                }

            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-offset-8">
            @if (loginUser.Id == Model.Id)
            {
                using (Html.BeginForm("ChangeCoverPic", "Users", FormMethod.Post, new {enctype = "multipart/form-data"}))
                {
                    <div class="row">
                        <span class="span4">
                                <input type="file" name="CoverPic" class="input-files" />
                            </span>
                        <span class="span2">
                                <input type="submit" name="coverPic" value="Upload" class="btn btn-upload" />
                            </span>
                    </div>
                }
            }
        </div>
    </div>

    @using (Html.BeginForm("PostStatus", "Status"))
    {
        <div class="row col-lg-8">
            <div class="panel panel-default" style="border: 1px solid #999999">
                <div class="panel-body">
                    <textarea name="Text" rows="4" class="form-control post-area" placeholder="Post Your Status"></textarea>
                    @*@Html.Editor("Text", new {htmlAttributes = new {@class = "form-control post-area"}})*@
                    <input type="hidden" value="@Model.Id" name="UserId">

                </div>
                <div class="row">
                    <div class="col-lg-offset-10">
                        <input type="submit" value="post" name="statusButton" class="btn btn-primary">
                    </div>
                </div>
            </div>

        </div>
    }



    @foreach (Status status in ViewBag.StatusList)
    {
        <div class="row col-lg-8">
            <div class="panel panel-default">
                @Model.FirstName @Model.LastName
                <div class="panel-body">


                    @using (Html.BeginForm("LikeStatus", "Status"))
                    {
                        <div>
                            @status.Text
                        </div>
                        <input type="hidden" value="@Model.Id" name="UserId">
                        <input type="hidden" value="@status.Id" name="StatusId">
                        <input type="submit" value="Like" name="likeButton" class="btn btn-link">
                    }

                    <p>Posted On: @status.Date</p>
                </div>
            </div>
        </div>
    }



</div>
@*<div class="col-lg-1">

                <div class="side-menu">
                    <!-- Place for the right menu bar-->

                </div>

            </div>*@
</div>
</div>


</body>
</html>